### ISSUE TITLE
Exception occured: Status Code: 401; Unauthorized 003_createInvoice.php

### ISSUE THREAD

**Issue by Gh0sTaR22** [btcpayserver/btcpayserver-php-client#20]
Hi guys,

I'm getting a 401 error Unauthorized when I try to create an Invoice using tutorial examples (script: 003_createInvoice.php) to my store at btcpayjungle.
I run this scripts perfectly 001_generateKeys.php and 002_pair.php but when I try to run the file 003_createInvoice.php I got this error:
![Capture3](https://user-images.githubusercontent.com/34281327/66003456-0e749d80-e49e-11e9-9832-e4ea551888e3.JPG)

I copy the token created in file 002_pair.php.

I changed the ports and the type mistake get_Sheme() as you can see below.
What is escaping me?

Ps: I already try to change the callback url but I had the same error.

![Capture](https://user-images.githubusercontent.com/34281327/66003989-8099b200-e49f-11e9-811f-1b7f431e2562.JPG)
![Capture1](https://user-images.githubusercontent.com/34281327/66003990-8099b200-e49f-11e9-8939-f348b9ac0055.JPG)
![Capture2](https://user-images.githubusercontent.com/34281327/66003991-8099b200-e49f-11e9-9ad7-af0f3b33e3b0.JPG)

**Comment by NicolasDorier** [comment]
why did you close?
