### ISSUE TITLE
Refund does not work completely, does not send email, no ipn refund

### ISSUE THREAD

**Issue by jomagalo** [btcpayserver/btcpayserver-php-client#40]
I don't really understand how the refund section works.

1. I proceed to create an invoice with requires a refund email activated.

2. The invoice payment is made.

3. The refund process begins.
    After the refund process is completed, an email never reaches the mailbox. There is also no change in the status of the refund 
    invoice. No notice by ipn on this issue. The mail server settings are configured and tested in server settings and stores. The 
    creation of the invoice is generated from the pay button.

Any further information on how refund works would be appreciated.

**Comment by Kukks** [comment]
> I don't really understand how the refund section works.
> 
> 1. I proceed to create an invoice with requires a refund email activated.
> 2. The invoice payment is made.
> 3. The refund process begins.
>    After the refund process is completed, an email never reaches the mailbox. There is also no change in the status of the refund
>    invoice. No notice by ipn on this issue. The mail server settings are configured and tested in server settings and stores. The
>    creation of the invoice is generated from the pay button.
> 
> Any further information on how refund works would be appreciated.

The refund api mentioned here does not work with btcpay.

**Comment by Kukks** [comment]
If you wish to implement refunds, check GreenField API instead: https://docs.btcpayserver.org/API/Greenfield/v1/#tag/Pull-payments-(Management)
