### ISSUE TITLE
Typo: Call to undefined method BTCPayServer\Client\Request::getSchema()

### ISSUE THREAD

**Issue by boooyu44** [btcpayserver/btcpayserver-php-client#49]
_Method BTCPayServer\Client\Request::__toString() must not throw an exception, caught Error: Call to **undefined method** BTCPayServer\Client\Request::getSchema()"_

File: **Client/Request.php**

There's typo in function getUriWithPort(). Should be getSchem**e**() not getSchem**a**(). Please fix it.
The library fails to create invoice while trying to migrate bitpay based project.
Error is triggered when creating invoice. When i fix this typo manually, all works.

  ```
/**
     * @inheritdoc
     */
    public function getUri()
    {
        return sprintf(
            '%s://%s/%s',
            $this->getScheme(), !!!!
            $this->getHost(),
            $this->getPath()
        );
    }
```

    /**
     * @inheritdoc
     */
    public function getUriWithPort()
    {
        return sprintf(
            '%s://%s:%s/%s',
            $this->getSchema(),       !!!!
            $this->getHost(),
            $this->getPort(),
            $this->getPath()
        );
    }

**Comment by woutersamaey** [comment]
Can you submit a PR?

**Comment by boooyu44** [comment]
Just for feedback. 

The issue has been long time fixed and spotted almost 2 years ago. I pulled ^1.0 instead of master.

https://github.com/btcpayserver/btcpayserver-php-client/commit/cfed65495f704136842aaa6529f4f674d31aee47

My fault :)
